// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf_nqYldDQBiPwDAdBWBY01L1RY30g-Pk',
    appId: '1:403132358646:web:12837d1af51788070ab1d7',
    messagingSenderId: '403132358646',
    projectId: 'aigrocerylist',
    authDomain: 'aigrocerylist.firebaseapp.com',
    storageBucket: 'aigrocerylist.firebasestorage.app',
    measurementId: 'G-QMQC474QFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnUUpfDxNtESBPTW1dQI2cCJWkxnnWrA',
    appId: '1:403132358646:android:dcab35931d75ac060ab1d7',
    messagingSenderId: '403132358646',
    projectId: 'aigrocerylist',
    storageBucket: 'aigrocerylist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC0cVkffJiiHO6KshHJKSNQPa3s5-TtZE',
    appId: '1:403132358646:ios:4c7af1620f0fd8460ab1d7',
    messagingSenderId: '403132358646',
    projectId: 'aigrocerylist',
    storageBucket: 'aigrocerylist.firebasestorage.app',
    iosBundleId: 'com.example.aishoppinglist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC0cVkffJiiHO6KshHJKSNQPa3s5-TtZE',
    appId: '1:403132358646:ios:4c7af1620f0fd8460ab1d7',
    messagingSenderId: '403132358646',
    projectId: 'aigrocerylist',
    storageBucket: 'aigrocerylist.firebasestorage.app',
    iosBundleId: 'com.example.aishoppinglist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf_nqYldDQBiPwDAdBWBY01L1RY30g-Pk',
    appId: '1:403132358646:web:60fe6f200b6565140ab1d7',
    messagingSenderId: '403132358646',
    projectId: 'aigrocerylist',
    authDomain: 'aigrocerylist.firebaseapp.com',
    storageBucket: 'aigrocerylist.firebasestorage.app',
    measurementId: 'G-E0W49BML9X',
  );
}
